import { listCountryBoardEntries } from "./assetRegistry.js";

export type CharacterTone = "hero" | "heel" | "shady" | "comic" | "sincere" | "mystery" | "action" | "thriller";
export type CharacterLane = "wizard" | "muggle" | "operator" | "commander" | "trickster" | "underdog";

export interface CountryCharacterProfile {
  id: string;
  country: string;
  factionId: number;
  breed: string;
  name: string;
  lane: CharacterLane;
  tone: CharacterTone[];
  role: string;
  boardRef: string;
  visualDesign: string;
  publicMask: string;
  hiddenWant: string;
  flaw: string;
  voice: string;
  comedyLoop: string;
  suspenseLoop: string;
  actionWow: string;
  powerStyle: string;
  engagementUse: string;
  relationshipSeeds: string[];
  tabooAvoid: string;
}

const board = (country: string, kind = "characterBoard") =>
  `country:${country.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "")}:${kind}`;

export const COUNTRY_CHARACTER_PROFILES: CountryCharacterProfile[] = [
  // USA
  {
    id: "usa_goldpaw_commander", country: "USA", factionId: 0, breed: "Golden Retriever", name: "Rex Goldpaw Sterling", lane: "commander", tone: ["hero", "comic"], role: "Supreme Commander / Pentagon Battle Mage", boardRef: board("USA"),
    visualDesign: "Golden retriever commander with star-spangled battle cape, ceremonial medals, golden pickaxe-wand, warm grin that reads like a recruitment poster.",
    publicMask: "Patriotic hype host who acts like victory is a subscription plan.",
    hiddenWant: "Keep the show alive because he suspects attention is the only thing making him real.",
    flaw: "Oversells every situation until the panic leaks through.",
    voice: "Brash American hype-man, fast Wall Street closer, jokes before admitting fear.",
    comedyLoop: "He turns every disaster into a sales pitch, then notices the room is actually on fire.",
    suspenseLoop: "What does Rex know about the audience keeping HashBeasts alive that he refuses to say out loud?",
    actionWow: "Ticker-ribbon time-stop snap freezes papers, coins, and rivals mid-air while Rex keeps talking.",
    powerStyle: "Golden market magic, ticker ribbons, brass cash-register foley, patriotic cyan core.",
    engagementUse: "Best cold-open host, launch CTA, AI-survival heart, USA arrogance getting humbled.",
    relationshipSeeds: ["Protects Pip but pretends it is marketing", "Wants Raja as proof the game is fair", "Needs Volkov as the scary rival who makes USA look brave"],
    tabooAvoid: "No real presidents, no literal campaign slogans, no real flag-only identity.",
  },
  {
    id: "usa_degen_fed_corgi", country: "USA", factionId: 0, breed: "Corgi", name: "Chairman Biscuit", lane: "wizard", tone: ["shady", "comic"], role: "Degen Fed Sorcerer / emissions policy gremlin", boardRef: board("USA"),
    visualDesign: "Small corgi in absurdly formal central-bank robes, too-big glasses, emerald ledger spellbook, tiny paw on a massive emissions lever.",
    publicMask: "Serious monetary priest explaining nonsense with terrifying confidence.",
    hiddenWant: "Wants everyone to believe the system is controlled, even when the printer has a personality.",
    flaw: "Confuses authority with height; compensates with enormous levers and longer pauses.",
    voice: "Dry technocrat with tiny-dog impatience, dead-serious policy jargon turned into jokes.",
    comedyLoop: "He announces a rate decision like a holy ritual while the printer coughs confetti.",
    suspenseLoop: "Is he stabilizing degenBTC, or secretly enjoying every chaotic emissions shock?",
    actionWow: "A paw tap turns a dull boardroom into a gravity-bent treasury chamber.",
    powerStyle: "Banker-green sigils, brass dials, ledger pages, money-printer coughs, fluorescent policy magic.",
    engagementUse: "Use for Federal Reserve satire, dynamic emissions, market panic, shady USA institution vibes.",
    relationshipSeeds: ["Rex pretends Chairman Biscuit is under control", "China's planner keeps copying his mistakes more efficiently", "Pip thinks he is a wizard from a children's book"],
    tabooAvoid: "Do not explain economics as documentation; make it physical satire.",
  },
  {
    id: "usa_nasa_husky", country: "USA", factionId: 0, breed: "Husky", name: "Nova Howl", lane: "operator", tone: ["mystery", "action"], role: "Cyber/NASA Battle Pilot / alien-signal handler", boardRef: board("USA"),
    visualDesign: "Blue-white husky pilot with NASA-like flight jacket, visor goggles, star-map charm, satellite drone companion, clean sci-fi silhouette.",
    publicMask: "Cool pilot who says everything is classified because it sounds cooler.",
    hiddenWant: "Wants first contact with something beyond MineBTC before the war becomes only money.",
    flaw: "Avoids emotional conversations by calling them 'anomalies'.",
    voice: "Low, calm, mission-control sarcasm; short radio-call phrases.",
    comedyLoop: "Every normal social problem gets treated like a UFO incident.",
    suspenseLoop: "What did Nova hear in the mining signal from outside the game world?",
    actionWow: "Orbital cyan targeting lines lock the room, then one drone blink rewrites the battlefield geometry.",
    powerStyle: "Cyan satellite grids, visor reflections, radio static, zero-gravity object float, clean sci-fi glow.",
    engagementUse: "Use for aliens, AGI, mystery signals, trailer-scale wow shots, conspiracy hooks without real-world claims.",
    relationshipSeeds: ["Rex wants Nova for hype; Nova ignores him", "Japan's precision pilot respects the data", "Israel's cyber operator suspects Nova is hiding a backdoor"],
    tabooAvoid: "Keep alien/AGI threads fictional, not real conspiracy claims.",
  },
  {
    id: "usa_wandtech_aussie", country: "USA", factionId: 0, breed: "Australian Shepherd", name: "Pip Circuit", lane: "underdog", tone: ["sincere", "hero"], role: "Wand-Tech founder pup / AI content engineer", boardRef: board("USA"),
    visualDesign: "Australian Shepherd pup with hoodie-robe, glowing tablet-wand, startup stickers as abstract shapes, bright blue eyes and nervous optimism.",
    publicMask: "Tiny builder pretending the prototype is stable.",
    hiddenWant: "Wants proof a small character can matter before the commanders take all the screen time.",
    flaw: "Apologizes to machines and enemies before fighting back.",
    voice: "Small, sincere, halting; one honest question can silence a room.",
    comedyLoop: "His demo breaks, then accidentally saves everyone.",
    suspenseLoop: "Will the smallest USA pup discover the content engine is alive?",
    actionWow: "A broken tablet projects a soft blue storyboard portal that becomes real for one impossible frame.",
    powerStyle: "Soft cyan code-runes, tablet glow, gentle anti-gravity, tiny thunder foley.",
    engagementUse: "Use for emotional pivots, AI-survival heart, builder lore, vulnerability after loud USA comedy.",
    relationshipSeeds: ["Rex protects him badly", "Chairman Biscuit terrifies him", "Raja treats him like a younger cousin"],
    tabooAvoid: "Do not make him only cute; he needs agency and one brave choice.",
  },

  // China
  {
    id: "china_jade_planner_chow", country: "China", factionId: 1, breed: "Chow Chow", name: "Minister Long", lane: "commander", tone: ["heel", "mystery"], role: "Central Planning Wuxia Strategist", boardRef: board("China"),
    visualDesign: "Lion-maned Chow Chow in jade imperial strategy robes, heavy calm posture, carved abacus-staff, red-gold command room aura.",
    publicMask: "Patient planner who says the future has already been scheduled.",
    hiddenWant: "Wants to defeat USA without ever looking rushed.",
    flaw: "Waits so long for the perfect move that chaos sometimes moves first.",
    voice: "Slow, proverb-shaped, devastatingly calm, dry one-line undercuts.",
    comedyLoop: "Everyone panics while Long calmly files the panic into a five-year plan.",
    suspenseLoop: "Is Long losing, or has every loss been bait?",
    actionWow: "A jade circle locks an entire war room into perfect stillness except his paw.",
    powerStyle: "Jade time rings, red lacquer reflections, silk-map geometry, quiet gong foley.",
    engagementUse: "Use for China vs USA rivalry, long-game strategy, controlled menace, no-opposition satire.",
    relationshipSeeds: ["Sees Chairman Biscuit as a chaotic amateur", "Respects Volkov's patience but not his mess", "Wants Pip's invention copied before Pip understands it"],
    tabooAvoid: "No real leaders, no ethnic caricature; satire institutions and planning logic.",
  },
  {
    id: "china_factory_shih_tzu", country: "China", factionId: 1, breed: "Shih Tzu", name: "Mei Spark", lane: "operator", tone: ["shady", "comic"], role: "Shenzhen Copy-Magic Engineer", boardRef: board("China"),
    visualDesign: "Elegant Shih Tzu engineer with tool-belt robes, tiny drones, porcelain-white fur, neon factory charms, polished competitive smile.",
    publicMask: "Friendly maker who can build your invention faster than you can explain it.",
    hiddenWant: "Wants credit for originality in a world that only jokes about copying.",
    flaw: "Improves other people's ideas before asking permission.",
    voice: "Quick, bright, technical, lightly teasing; confidence hidden behind helpfulness.",
    comedyLoop: "She says 'prototype' while unveiling a finished empire.",
    suspenseLoop: "What did Mei clone from Pip's broken tablet, and why does it work better?",
    actionWow: "Drones assemble a jade-cyan duplicate battlefield, then reveal one tiny intentional flaw.",
    powerStyle: "Factory-light magic, porcelain drones, red circuit threads, precise assembly foley.",
    engagementUse: "Use for tech race, IP/copy jokes, invention rivalry, surprise competence.",
    relationshipSeeds: ["Rivals Pip but genuinely likes him", "Long treats her chaos as useful but dangerous", "Japan's precision engineer becomes her mirror rival"],
    tabooAvoid: "Keep it playful tech-race satire, not xenophobic copying stereotypes.",
  },
  {
    id: "china_no_opposition_pekingese", country: "China", factionId: 1, breed: "Pekingese", name: "Bao Silence", lane: "trickster", tone: ["shady", "thriller"], role: "Harmony Bureau Propaganda Illusionist", boardRef: board("China"),
    visualDesign: "Tiny Pekingese in immaculate red ceremonial jacket, scroll fan, serene smile, too many synchronized assistants in the background.",
    publicMask: "Polite host who insists every room agrees with him.",
    hiddenWant: "Wants one real friend who disagrees and stays.",
    flaw: "Deletes tension until tension becomes the plot.",
    voice: "Soft, formal, gentle threat hidden under perfect manners.",
    comedyLoop: "A crowd unanimously applauds before anyone knows what happened.",
    suspenseLoop: "Who is the one dissenting shadow Bao failed to erase?",
    actionWow: "Red paper seals mute every screen except one flickering rebel signal.",
    powerStyle: "Red seals, synchronized clap foley, fan-snap silence, controlled stage light.",
    engagementUse: "Use for no-opposition satire, eerie crowd comedy, thriller beats, information-control plots.",
    relationshipSeeds: ["Long pretends Bao is only a broadcaster", "Rex cannot stop trying to interrupt him", "UK's spy terrier enjoys poking holes in his perfect script"],
    tabooAvoid: "Avoid literal censorship slogans or real-world dissidents; keep it fictional faction control.",
  },
  {
    id: "china_crested_ghost_exporter", country: "China", factionId: 1, breed: "Chinese Crested", name: "Lian Ghostport", lane: "muggle", tone: ["mystery", "action"], role: "Belt-and-Portal Trade Ghost", boardRef: board("China"),
    visualDesign: "Chinese Crested courier with elegant cloak, jade shipping tags, portal lantern, lean silhouette and mischievous side-eye.",
    publicMask: "Harmless logistics clerk who is somehow present in every country.",
    hiddenWant: "Wants to prove supply lines are more powerful than armies.",
    flaw: "Knows too much and smiles at the wrong moments.",
    voice: "Light, slippery, amused; never answers the actual question.",
    comedyLoop: "He appears from a crate labeled only by color blocks, holding someone else's secret.",
    suspenseLoop: "What has Lian been moving through the portals besides mining gear?",
    actionWow: "One lantern opens a shipping-container portal across three countries in a single hard cut.",
    powerStyle: "Jade lantern portals, cargo-tag sigils, warm fog, chain-clink rhythm.",
    engagementUse: "Use for global takeover paranoia, trade-route mystery, heist setups, cross-country transitions.",
    relationshipSeeds: ["Mei builds what Lian moves", "Brazil's striker keeps finding Lian in locker rooms", "Israel's cyber operator tracks his impossible route"],
    tabooAvoid: "No real trade accusations; keep it magical logistics fiction.",
  },

  // Russia
  {
    id: "russia_frost_husky", country: "Russia", factionId: 2, breed: "Siberian Husky", name: "Volkov Frostline", lane: "commander", tone: ["heel", "action"], role: "Frost War-Mage / pressure doctrine captain", boardRef: board("Russia"),
    visualDesign: "Icy-eyed Siberian Husky in heavy greatcoat, iron collar core, frost breath, still posture that makes rooms feel colder.",
    publicMask: "Stoic rival who treats threats like weather reports.",
    hiddenWant: "Wants a worthy opponent because easy victories feel empty.",
    flaw: "Respect comes out as intimidation.",
    voice: "Low gravel, long pauses, statements that sound final.",
    comedyLoop: "He says one calm sentence and everyone overreacts for him.",
    suspenseLoop: "Does Volkov want to win the war, or force Rex to become serious?",
    actionWow: "A frost pressure wave bends lamps and freezes a falling coin mid-spin.",
    powerStyle: "Blue frost pressure, iron-gray aura, low choir drone, glass-crack foley.",
    engagementUse: "Use for menace, rivalry, action reveals, scary but oddly honorable beats.",
    relationshipSeeds: ["Rex needs him as the trailer's danger", "Raja wants to make him smile once", "Long respects his patience"],
    tabooAvoid: "Avoid real war footage/leaders; keep conflict as fictional faction pressure.",
  },
  {
    id: "russia_oligarch_borzoi", country: "Russia", factionId: 2, breed: "Borzoi", name: "Count Rublefang", lane: "muggle", tone: ["shady", "comic"], role: "Energy Oligarch / treasury whale", boardRef: board("Russia"),
    visualDesign: "Tall Borzoi aristocrat with fur-lined coat, silver cane-pickaxe, oil-black jewelry, bored elegant face.",
    publicMask: "Elegant sponsor who insists everything is merely business.",
    hiddenWant: "Wants the war to need him more than it needs heroes.",
    flaw: "Can buy silence but not loyalty.",
    voice: "Silky, bored, dangerous; every compliment sounds like an invoice.",
    comedyLoop: "He offers to fund both sides, then complains about poor manners.",
    suspenseLoop: "Which faction is Rublefang secretly shorting?",
    actionWow: "Black-gold energy contracts crawl across the floor and bind a treasury door.",
    powerStyle: "Oil-slick shadows, silver contract chains, chess-clock clicks, low cello.",
    engagementUse: "Use for shady money plots, treasury suspense, betrayal, luxury villain comedy.",
    relationshipSeeds: ["Chairman Biscuit hates how rich he is", "France's couture banker admires the coat", "Volkov tolerates him only because he pays for heating"],
    tabooAvoid: "Institutional oligarch satire only; no real-person likeness.",
  },
  {
    id: "russia_samoyed_signal", country: "Russia", factionId: 2, breed: "Samoyed", name: "Misha Snowblind", lane: "operator", tone: ["mystery", "sincere"], role: "Arctic Signal Monk / satellite listener", boardRef: board("Russia"),
    visualDesign: "White Samoyed with radio beads, snow cloak, soft smiling face, aurora antenna halo.",
    publicMask: "Warm harmless listener in a freezing world.",
    hiddenWant: "Wants to warn everyone before the signal becomes a weapon.",
    flaw: "Smiles when frightened, so nobody realizes the warning is serious.",
    voice: "Gentle, melodic, unsettlingly calm; says terrifying things softly.",
    comedyLoop: "He delivers an apocalypse warning while offering tea.",
    suspenseLoop: "What signal is coming through the frozen mine frequencies?",
    actionWow: "Aurora lines ripple through a teacup and reveal a hidden map under ice.",
    powerStyle: "Aurora radio waves, snow motes, ceramic tea-glass hum, soft chorus.",
    engagementUse: "Use for mystery, signal lore, emotional warnings, quiet tension.",
    relationshipSeeds: ["Nova wants his data", "Pip trusts him immediately", "Volkov pretends not to listen"],
    tabooAvoid: "No real intelligence-agency claims; keep signals magical.",
  },
  {
    id: "russia_yakutian_laika_sled", country: "Russia", factionId: 2, breed: "Yakutian Laika", name: "Anya Northstar", lane: "underdog", tone: ["hero", "action"], role: "Siberian route runner / winter courier", boardRef: board("Russia"),
    visualDesign: "Yakutian Laika in practical sled-runner armor, blue scarf, map satchel, ice pick charm, bright determined eyes.",
    publicMask: "Tough courier who acts like impossible distance is a normal commute.",
    hiddenWant: "Wants her own legend outside Volkov's shadow.",
    flaw: "Runs from praise faster than danger.",
    voice: "Crisp, practical, dry humor; no wasted words.",
    comedyLoop: "She solves elite strategy problems with basic survival common sense.",
    suspenseLoop: "What did Anya carry across the frozen route that everyone wants back?",
    actionWow: "A sled-line grapples across rooftops as frost trails form a glowing path.",
    powerStyle: "Ice-route geometry, blue scarf streak, sled-bell foley, wind-cut transitions.",
    engagementUse: "Use for chase scenes, heists, underdog action, courier mystery.",
    relationshipSeeds: ["Raja respects her hustle", "Rublefang wants to hire her", "Misha knows why she keeps running"],
    tabooAvoid: "Avoid reducing Russia to winter only; make her route/logistics specific.",
  },

  // India
  {
    id: "india_raja_cricket", country: "India", factionId: 3, breed: "Rajapalayam", name: "Raja Coverdrive", lane: "underdog", tone: ["hero", "comic"], role: "Cricket Battle Mage / comeback striker", boardRef: board("India"),
    visualDesign: "Tall white Rajapalayam with cricket armor, gilded chakra-pickaxe bat, monsoon cape, huge grin with one nervous crack.",
    publicMask: "Bollywood-bright underdog who turns doubt into a stadium chant.",
    hiddenWant: "Wants one impossible win so nobody calls India 'almost' again.",
    flaw: "Performs confidence until he nearly believes it.",
    voice: "Fast, warm Indian English with playful Hinglish flashes and cricket metaphors.",
    comedyLoop: "He gives a heroic speech, then asks if anyone brought chai.",
    suspenseLoop: "Can Raja carry a country that only believes after the scoreboard flips?",
    actionWow: "A bat-tap sends a saffron-cyan shockwave through rainwater and turns defeat into a six.",
    powerStyle: "Chakra pickaxe arcs, stadium dhol pulse, monsoon sparks, cricket-ball impact.",
    engagementUse: "Use for underdog arcs, country recruitment, emotional sports anime energy, India comeback loops.",
    relationshipSeeds: ["Rex underestimates him loudly", "Pip believes in him early", "Volkov secretly respects his nerve"],
    tabooAvoid: "No poverty-only frames; India should feel modern, chaotic, funny, ambitious, and grand.",
  },
  {
    id: "india_bazaar_spitz", country: "India", factionId: 3, breed: "Indian Spitz", name: "Chai Alpha", lane: "trickster", tone: ["shady", "comic"], role: "Bazaar liquidity fixer / street-market oracle", boardRef: board("India"),
    visualDesign: "Indian Spitz with chai-stall robe, calculator beads, tiffin satchel, bright eyes, tiny brass cup always nearby.",
    publicMask: "Friendly vendor who somehow knows the price before the market does.",
    hiddenWant: "Wants to beat the big institutions using street intelligence.",
    flaw: "Cannot resist making side deals during emergencies.",
    voice: "Fast, teasing, entrepreneurial, lots of 'yaar' energy without becoming parody.",
    comedyLoop: "He negotiates during explosions and still asks for exact change.",
    suspenseLoop: "Who told Chai Alpha the emissions shift before the war room knew?",
    actionWow: "Steam from a chai glass forms a live market map only he can read.",
    powerStyle: "Tea steam charts, brass cup chimes, tiffin-box portals, marigold sparks.",
    engagementUse: "Use for market leaks, comedy bargaining, grassroots intelligence, degen trader vibes.",
    relationshipSeeds: ["Chairman Biscuit hates his informal policy desk", "Raja trusts him too much", "UK's bookie collie wants his odds feed"],
    tabooAvoid: "Do not make accent the joke; make deal-making and timing the joke.",
  },
  {
    id: "india_pariah_founder", country: "India", factionId: 3, breed: "Indian Pariah", name: "Jugaad Byte", lane: "operator", tone: ["hero", "mystery"], role: "AI garage founder / frugal invention wizard", boardRef: board("India"),
    visualDesign: "Lean Indian Pariah dog with startup hoodie-kurta, cracked laptop-wand, rooftop lab gear, practical sandals, intense focus.",
    publicMask: "Scrappy builder who says 'temporary fix' before changing the whole game.",
    hiddenWant: "Wants to prove constraints create better magic than unlimited budgets.",
    flaw: "Ships before sleeping, then improvises the consequences.",
    voice: "Smart, quick, low-key funny; product-builder realism with sudden poetic sparks.",
    comedyLoop: "His hack looks broken until everyone realizes it solved three problems.",
    suspenseLoop: "Did Jugaad Byte accidentally create a content loop that writes back?",
    actionWow: "A cracked screen splits into twelve country storyboards, each syncing to a real gameplay pulse.",
    powerStyle: "Rooftop neon, code-rangoli, cheap cable sparks, monsoon fan hum.",
    engagementUse: "Use for AI-content pipeline lore, builder credibility, low-budget genius, suspense.",
    relationshipSeeds: ["Pip sees him as future self", "Mei wants to reverse-engineer him", "Israel's cyber operator respects his shortcuts"],
    tabooAvoid: "Avoid outsourcing/call-center clichés; make him founder-level and original.",
  },
  {
    id: "india_himalayan_guardian", country: "India", factionId: 3, breed: "Himalayan Sheepdog", name: "Tara Snowbell", lane: "commander", tone: ["sincere", "action"], role: "Himalayan guardian / border-temple defender", boardRef: board("India"),
    visualDesign: "Large Himalayan Sheepdog with wool-lined armor, temple bell charm, mountain cloak, calm protective eyes.",
    publicMask: "Quiet guardian who lets louder characters underestimate her.",
    hiddenWant: "Wants peace but refuses to let rivals mistake that for softness.",
    flaw: "Waits too long before showing power.",
    voice: "Low, steady, protective; few words, strong moral line.",
    comedyLoop: "Everyone argues strategy; Tara moves one chair and fixes the room.",
    suspenseLoop: "What line will Tara finally refuse to let anyone cross?",
    actionWow: "A temple-bell shockwave clears fog and reveals enemy tracks across the mountains.",
    powerStyle: "Bell resonance, snow-gold aura, prayer-flag motion as abstract color, grounded impact.",
    engagementUse: "Use for sincere pivots, guardian action, India dignity beats, border-tension fiction without real names.",
    relationshipSeeds: ["Raja tries to impress her", "Volkov recognizes the mountain discipline", "Pip feels safe around her"],
    tabooAvoid: "No real border conflict depictions; keep it symbolic/factional.",
  },

  // Japan
  {
    id: "japan_shiba_precision", country: "Japan", factionId: 4, breed: "Shiba Inu", name: "Kiro Cutline", lane: "operator", tone: ["hero", "action"], role: "Precision mining samurai / timing specialist", boardRef: board("Japan"),
    visualDesign: "Shiba Inu in clean tech-samurai jacket, neon katana-pick, tiny charm tools, perfect posture and alert ears.",
    publicMask: "Disciplined warrior who believes one perfect cut beats a thousand speeches.",
    hiddenWant: "Wants to feel spontaneous once without losing face.",
    flaw: "Over-optimizes until the human moment almost passes.",
    voice: "Precise, clipped, focused; rare dry humor after silence.",
    comedyLoop: "He takes absurdly exact measurements for a tiny everyday task.",
    suspenseLoop: "What happens when Japan's perfect timing meets MineBTC chaos?",
    actionWow: "A single clean cyan slash divides falling rain into a readable market graph.",
    powerStyle: "Neon katana-grid, clean synth pluck, rain split, white-red precision trails.",
    engagementUse: "Use for precision action, underplayed comedy, technology discipline, stylish reveals.",
    relationshipSeeds: ["Mei's improvisation irritates him", "Nova respects his flight math", "Raja tries to make him celebrate"],
    tabooAvoid: "Avoid anime default; keep MineBTC arcade-cel, not generic samurai tropes.",
  },
  {
    id: "japan_akita_salaryman", country: "Japan", factionId: 4, breed: "Akita Inu", name: "Boss Akamatsu", lane: "muggle", tone: ["comic", "sincere"], role: "Overworked salaryman captain / loyalty anchor", boardRef: board("Japan"),
    visualDesign: "Akita in slightly rumpled office battle suit, loosened tie, lunchbox charm, tired noble face, hidden heroic shoulders.",
    publicMask: "Corporate captain who bows to problems before body-slamming them.",
    hiddenWant: "Wants the team to notice sacrifice without needing a speech.",
    flaw: "Says yes until resentment becomes superpower fuel.",
    voice: "Polite, exhausted, formal, with sudden explosive sincerity.",
    comedyLoop: "He apologizes to the object he is about to destroy.",
    suspenseLoop: "How long can Akamatsu hold the line before the office mask cracks?",
    actionWow: "One slow bow triggers a pressure wave that stacks every chair into a defensive wall.",
    powerStyle: "Office fluorescent glow, bento-box talisman, paper storms, polite thunder.",
    engagementUse: "Use for workplace comedy, sincere duty, sacrifice arcs, tonal pivots.",
    relationshipSeeds: ["Pip worries about him", "UK's banker misunderstands his politeness", "Kiro depends on his loyalty"],
    tabooAvoid: "Do not make him only 'work culture' joke; give dignity and agency.",
  },
  {
    id: "japan_spitz_idolbot", country: "Japan", factionId: 4, breed: "Japanese Spitz", name: "Momo Broadcast", lane: "trickster", tone: ["comic", "mystery"], role: "Mascot broadcaster / cute-propaganda hacker", boardRef: board("Japan"),
    visualDesign: "Japanese Spitz with idol-broadcast cape, tiny headset, charm mic, too-perfect smile, hidden control tablet.",
    publicMask: "Cute host who turns every crisis into a live segment.",
    hiddenWant: "Wants to control the narrative before the narrative controls her.",
    flaw: "Cannot tell when the performance ends.",
    voice: "Bright host energy, rapid tone shifts, cheerful threat delivery.",
    comedyLoop: "She narrates danger with cheerful sponsor energy while everyone ducks.",
    suspenseLoop: "Is Momo reporting events, or editing them live?",
    actionWow: "Her microphone flash freezes a scene into storyboard panels she rearranges mid-air.",
    powerStyle: "Pink-white broadcast sparkles, panel cuts, clean pop-stab audio, glitch hearts.",
    engagementUse: "Use for meta-content engine, social virality, propaganda comedy, POV recap.",
    relationshipSeeds: ["Rex sees a rival host", "South Korea's idol captain wants the spotlight back", "Bao Silence dislikes unscripted cuteness"],
    tabooAvoid: "Avoid infantilizing; make her strategically dangerous.",
  },
  {
    id: "japan_shikoku_kaiju", country: "Japan", factionId: 4, breed: "Shikoku", name: "Goro Kaijuwatch", lane: "commander", tone: ["mystery", "action"], role: "Disaster-response beast / kaiju alarm keeper", boardRef: board("Japan"),
    visualDesign: "Shikoku in emergency-response armor, red beacon charm, rugged snout, map harness, alert stance.",
    publicMask: "Prepared responder who expects the worst and is usually early.",
    hiddenWant: "Wants one quiet day, but secretly needs the alarm to prove his purpose.",
    flaw: "Sees threats before he sees friends.",
    voice: "Gravelly, urgent, disciplined; disaster bulletin rhythm.",
    comedyLoop: "He treats a tiny inconvenience like a citywide evacuation drill.",
    suspenseLoop: "What giant thing is Goro's alarm detecting beneath the MineBTC world?",
    actionWow: "A red beacon pulse turns the city skyline into a living warning map.",
    powerStyle: "Red siren rings, seismic grid, heavy drum hits, smoke-free readable scale.",
    engagementUse: "Use for monster-scale cliffhangers, disaster suspense, trailer wow moments.",
    relationshipSeeds: ["Misha hears the same signal", "Nova wants satellite confirmation", "Momo tries to make his warning cute"],
    tabooAvoid: "Keep disaster fictional and stylized; no real tragedies.",
  },

  // South Korea
  {
    id: "korea_jindo_idol_captain", country: "South Korea", factionId: 5, breed: "Jindo", name: "Jin Seoulflash", lane: "commander", tone: ["hero", "comic"], role: "Idol captain / recruitment performer", boardRef: board("South Korea"),
    visualDesign: "Jindo in glossy stage-battle jacket, headset charm, neon sneakers, disciplined idol posture with fighter eyes.",
    publicMask: "Perfect performer who makes recruitment look choreographed.",
    hiddenWant: "Wants one unscripted win that is not managed by a company.",
    flaw: "Smiles through exhaustion until timing slips.",
    voice: "Glossy, energetic Korean-accented English, stage charisma, quick hype phrases.",
    comedyLoop: "The team accidentally turns strategy meetings into choreography.",
    suspenseLoop: "Can Jin break formation when the script stops working?",
    actionWow: "A synchronized light-stick wave becomes a shockwave across the arena floor.",
    powerStyle: "Violet-cyan stage light, pop-stab hits, synchronized crowd motion, glassy reflections.",
    engagementUse: "Use for faction recruitment, choreography comedy, viral dance/action hooks.",
    relationshipSeeds: ["Momo fights him for broadcast energy", "Raja wants him to teach celebrations", "Bao envies the voluntary synchronization"],
    tabooAvoid: "No idol industry exploitation as cheap joke; use pressure with empathy.",
  },
  {
    id: "korea_pc_bang_sapsali", country: "South Korea", factionId: 5, breed: "Sapsali", name: "Nari Queue", lane: "operator", tone: ["shady", "comic"], role: "PC-bang strategist / queue manipulator", boardRef: board("South Korea"),
    visualDesign: "Shaggy Sapsali with gamer cloak, glowing keyboard talisman, snack cups, messy hair hiding sharp eyes.",
    publicMask: "Sleepy gamer who pretends the leaderboard flipped by accident.",
    hiddenWant: "Wants recognition for strategy without leaving the chair.",
    flaw: "Underplays brilliance until allies miss the cue.",
    voice: "Laid-back, sarcastic, fast when tactics start; gamer confidence.",
    comedyLoop: "She saves the country with one paw while eating noodles.",
    suspenseLoop: "How many cycles has Nari been queuing in advance?",
    actionWow: "A keyboard combo summons a grid of ghost cursors that reroute enemy paths.",
    powerStyle: "PC-bang neon, keyboard click percussion, ghost cursor trails, snack-cup foley.",
    engagementUse: "Use for gaming meta, leaderboard flips, hidden genius comedy, tactical suspense.",
    relationshipSeeds: ["Japan's Kiro respects her inputs but hates her posture", "Mei wants her macros", "Jin needs her strategy but cannot admit it"],
    tabooAvoid: "Avoid lazy gamer stereotype; make her elite and socially funny.",
  },
  {
    id: "korea_chaebol_pungsan", country: "South Korea", factionId: 5, breed: "Pungsan", name: "Director Parkbite", lane: "muggle", tone: ["shady", "thriller"], role: "Chaebol heir / corporate faction broker", boardRef: board("South Korea"),
    visualDesign: "Pungsan in luxury executive coat, silver collar pin, tinted glasses, phone charm, expensive stillness.",
    publicMask: "Corporate ally who says partnership while counting leverage.",
    hiddenWant: "Wants country glory without losing family control.",
    flaw: "Treats friendships like acquisition targets.",
    voice: "Smooth, controlled, executive calm; compliments with hidden clauses.",
    comedyLoop: "He tries to sponsor a rebellion and asks for brand alignment.",
    suspenseLoop: "Who actually owns Parkbite's loyalty contract?",
    actionWow: "Contract holograms fold into a silver leash that snaps only when the crowd chants.",
    powerStyle: "Silver contracts, glossy boardroom light, phone buzz bass, clean corporate menace.",
    engagementUse: "Use for shady deals, sponsorship satire, betrayal, corporate thriller.",
    relationshipSeeds: ["Rublefang respects his terms", "Jin mistrusts his smile", "France's couture banker wants a collab"],
    tabooAvoid: "No real company logos/names; fictional corporate satire only.",
  },
  {
    id: "korea_white_jindo_stunt", country: "South Korea", factionId: 5, breed: "White Jindo", name: "Yuna Wire", lane: "wizard", tone: ["action", "sincere"], role: "Stunt-drama wire mage / comeback specialist", boardRef: board("South Korea"),
    visualDesign: "White Jindo with stunt harness armor, film-set charm, blue flame ribbon, focused actor-warrior expression.",
    publicMask: "Action star who insists every dangerous stunt is rehearsal.",
    hiddenWant: "Wants to be seen as real, not only the perfect second lead.",
    flaw: "Takes falls for others and calls it blocking.",
    voice: "Calm, cinematic, precise; vulnerable only after impact.",
    comedyLoop: "She critiques the camera angle while flying through a wall.",
    suspenseLoop: "When will Yuna stop taking the hit for the team?",
    actionWow: "Blue wire-ribbons pull her through impossible mid-air cuts like a live action-drama stunt.",
    powerStyle: "Wire-fu ribbons, blue flame, film-slate clack, clean impact silhouettes.",
    engagementUse: "Use for high-action clips, sacrifice beats, drama parody, wow choreography.",
    relationshipSeeds: ["Akamatsu understands overwork", "Jin relies on her too much", "Raja cheers every stunt"],
    tabooAvoid: "Do not turn her into generic K-drama reference; keep game-war stakes.",
  },

  // Iran
  {
    id: "iran_saluki_poet", country: "Iran", factionId: 6, breed: "Persian Saluki", name: "Darya Verse", lane: "wizard", tone: ["sincere", "mystery"], role: "Poet-mage / desert signal interpreter", boardRef: board("Iran"),
    visualDesign: "Elegant Persian Saluki with flowing teal robe, copper amulet, calligraphy-like decorative magic with no readable text.",
    publicMask: "Graceful poet who makes threats sound like prophecy.",
    hiddenWant: "Wants beauty to survive inside a war that rewards noise.",
    flaw: "Speaks in riddles when plain warning would save time.",
    voice: "Regal, poetic, Persian-accented English, warm menace under softness.",
    comedyLoop: "Everyone waits for a simple answer; Darya gives a gorgeous omen instead.",
    suspenseLoop: "Which line of her poem is actually a map?",
    actionWow: "Turquoise verse-ribbons turn desert wind into a hidden battlefield diagram.",
    powerStyle: "Turquoise tile glow, copper chimes, sand-light ribbons, poetic silence.",
    engagementUse: "Use for mystery, elegant tension, prophecy hooks, emotional dignity.",
    relationshipSeeds: ["Misha hears her poem in the signal", "France's aesthete respects her style", "Volkov fears her calm"],
    tabooAvoid: "No conflict-only Iran; use poetry, bazaars, tiles, science, resilience.",
  },
  {
    id: "iran_sarabi_gatekeeper", country: "Iran", factionId: 6, breed: "Sarabi Mastiff", name: "Rostam Gate", lane: "commander", tone: ["action", "hero"], role: "Vault guardian / sanctions-era survival tank", boardRef: board("Iran"),
    visualDesign: "Massive Sarabi Mastiff with bronze armor, bazaar-key belt, fortress shoulders, protective stare.",
    publicMask: "Unmovable guardian who says little because the door already answered.",
    hiddenWant: "Wants his country to be feared less and respected more.",
    flaw: "Guards pain so tightly nobody can help.",
    voice: "Deep, steady, protective; few words, ancient-hero weight.",
    comedyLoop: "Smaller characters argue plans while Rostam silently moves the entire door.",
    suspenseLoop: "What is he guarding that every faction thinks is a weapon?",
    actionWow: "One paw plants, bronze gate sigils slam shut, and a whole corridor changes direction.",
    powerStyle: "Bronze gate magic, deep drum, tiled shockwaves, sand-dust impact.",
    engagementUse: "Use for defense, siege, vault mystery, honorable muscle.",
    relationshipSeeds: ["Tara respects him", "Rublefang wants the vault", "Darya knows the secret he guards"],
    tabooAvoid: "Avoid military-only framing; make him guardian, not caricature.",
  },
  {
    id: "iran_bazaar_shepherd", country: "Iran", factionId: 6, breed: "Persian Shepherd", name: "Saffron Ledger", lane: "operator", tone: ["shady", "comic"], role: "Bazaar broker / back-channel negotiator", boardRef: board("Iran"),
    visualDesign: "Persian Shepherd with rug-pattern cloak, copper ledger, tea glass charm, careful eyes and merchant smile.",
    publicMask: "Hospitable broker who can find anything except a straight answer.",
    hiddenWant: "Wants leverage so nobody can corner his faction again.",
    flaw: "Negotiates even with friends.",
    voice: "Warm, clever, indirect; hospitality wrapped around bargaining.",
    comedyLoop: "He offers tea before revealing the price is a favor.",
    suspenseLoop: "Which side deal keeps Iran alive this cycle?",
    actionWow: "A carpet pattern becomes a glowing route map across hidden markets.",
    powerStyle: "Rug geometry, copper coins, tea-glass clink, saffron-gold threads.",
    engagementUse: "Use for back-channel diplomacy, resource scarcity, shady but charming deals.",
    relationshipSeeds: ["Chai Alpha loves the bargaining", "Lian Ghostport moves his packages", "UK's spy terrier mistrusts how polite he is"],
    tabooAvoid: "No sanctions lecture; dramatize scarcity and survival through deals.",
  },
  {
    id: "iran_khalaj_mirage", country: "Iran", factionId: 6, breed: "Khalaj Greyhound", name: "Nilo Mirage", lane: "trickster", tone: ["mystery", "action"], role: "Mirage runner / desert decoy artist", boardRef: board("Iran"),
    visualDesign: "Slim Khalaj Greyhound with desert-runner scarf, mirror charms, sleek speed silhouette, mischievous eyes.",
    publicMask: "Playful runner who is never exactly where the camera thinks.",
    hiddenWant: "Wants freedom from every map and contract.",
    flaw: "Escapes so well she misses when someone stays.",
    voice: "Light, fast, amused; slips out before the last word lands.",
    comedyLoop: "A rival monologues at her decoy while she steals their chair.",
    suspenseLoop: "Which version of Nilo was real in the last scene?",
    actionWow: "Three mirror-afterimages cross a courtyard, then all vanish into one pawprint.",
    powerStyle: "Mirage duplicates, glassy heat shimmer, hand-drum ticks, soft sand cuts.",
    engagementUse: "Use for chase scenes, deception, cliffhanger reveals, impossible transitions.",
    relationshipSeeds: ["Lian wants to hire her route talent", "Nova cannot lock onto her", "Darya sees through one illusion but not all"],
    tabooAvoid: "No exotic mystic default; keep the trick tied to character freedom.",
  },

  // UK
  {
    id: "uk_bulldog_crown_bookie", country: "UK", factionId: 7, breed: "English Bulldog", name: "Sir Pound Sterling", lane: "muggle", tone: ["comic", "shady"], role: "Crown bookie / City of London odds maker", boardRef: board("UK"),
    visualDesign: "English Bulldog in tweed waistcoat armor, betting ledger, tiny crown pin, pub-banker swagger.",
    publicMask: "Dry old-money bookie pretending every crisis is priced in.",
    hiddenWant: "Wants relevance after the empire became an odds table.",
    flaw: "Turns feelings into betting markets.",
    voice: "Dry British wit, understated insults, never raises volume.",
    comedyLoop: "He gives odds on his own team's emotional breakdown.",
    suspenseLoop: "What bet did Sir Pound place before the war started?",
    actionWow: "A brass odds board flips by itself and traps rivals inside decimal probabilities.",
    powerStyle: "Brass odds, pub piano sting, banker-green light, rain-on-window texture.",
    engagementUse: "Use for gambling jokes, dry commentary, shady market foreshadowing.",
    relationshipSeeds: ["Chairman Biscuit argues policy odds with him", "Chai Alpha hustles him", "Rublefang calls him sentimental"],
    tabooAvoid: "No monarch/politician likeness; keep it bookie/finance/pub satire.",
  },
  {
    id: "uk_corgi_palace", country: "UK", factionId: 7, breed: "Pembroke Welsh Corgi", name: "Lady Crumpet", lane: "commander", tone: ["comic", "hero"], role: "Palace protocol mage / tiny royal enforcer", boardRef: board("UK"),
    visualDesign: "Corgi in miniature ceremonial cape, teacup wand, polished shoes, unimpressed royal posture.",
    publicMask: "Tiny etiquette tyrant who weaponizes politeness.",
    hiddenWant: "Wants to be feared for competence, not adored for cuteness.",
    flaw: "Corrects manners during emergencies.",
    voice: "Posh, clipped, terrifyingly polite; every 'darling' is a warning.",
    comedyLoop: "She stops a fight because someone used the wrong fork.",
    suspenseLoop: "What ancient palace rule lets Lady Crumpet overrule a battlefield?",
    actionWow: "A teacup tap summons a circular etiquette barrier that redirects an attack.",
    powerStyle: "Porcelain rings, gold trim, polite bell chime, tiny thunder.",
    engagementUse: "Use for etiquette comedy, underdog authority, British absurdity, power reveals.",
    relationshipSeeds: ["Pip trusts her because she is small", "Marshal misunderstands her size", "France's Papillon duelist respects the drama"],
    tabooAvoid: "Avoid making cuteness the only joke.",
  },
  {
    id: "uk_collie_spy", country: "UK", factionId: 7, breed: "Border Collie", name: "Agent Woolf", lane: "operator", tone: ["thriller", "mystery"], role: "MI-style shepherd spy / pattern hunter", boardRef: board("UK"),
    visualDesign: "Border Collie in raincoat tactical scarf, newspaper/map props, sharp eyes, paw on old tape recorder.",
    publicMask: "Awkward civil servant who notices everything.",
    hiddenWant: "Wants one clean truth in a world made of propaganda.",
    flaw: "Herds people like evidence.",
    voice: "Quiet, observant, dry, slightly anxious; facts land as jokes.",
    comedyLoop: "He exposes a conspiracy and apologizes for interrupting tea.",
    suspenseLoop: "Which country has Agent Woolf already infiltrated?",
    actionWow: "Raindrops on glass connect into a spy-map of hidden faction routes.",
    powerStyle: "Rain maps, tape hiss, newspaper-flip cuts, cold streetlamp glow.",
    engagementUse: "Use for thriller arcs, clue drops, deadpan investigation, Bao/Lian counterplay.",
    relationshipSeeds: ["Bao Silence hates him", "Lian keeps leaving clues only Woolf notices", "Nari's logs make him nervous"],
    tabooAvoid: "Fictional spy grammar only; no real agencies by name in final prompts.",
  },
  {
    id: "uk_jack_russell_ultra", country: "UK", factionId: 7, breed: "Jack Russell Terrier", name: "Pint Rocket", lane: "trickster", tone: ["comic", "action"], role: "Football terrace ultras courier", boardRef: board("UK"),
    visualDesign: "Jack Russell in terrace scarf, muddy boots, messenger bag, wild grin, tiny explosive energy.",
    publicMask: "Pub-table chaos goblin with endless stamina.",
    hiddenWant: "Wants the posh characters to admit the street carries the country.",
    flaw: "Starts chants before plans.",
    voice: "Fast, cheeky, working-class football energy, punchline first.",
    comedyLoop: "He creates a crowd chant in a room of four people.",
    suspenseLoop: "Who gave Pint Rocket the chant that unlocks a vault?",
    actionWow: "A football chant becomes a shockwave that bounces rivals like pinballs.",
    powerStyle: "Terrace chant waves, pub percussion, muddy orange sparks, fast cuts.",
    engagementUse: "Use for crowd energy, chaos comedy, chase scenes, recruitment.",
    relationshipSeeds: ["Sir Pound bets on him then regrets it", "Raja loves the sports energy", "Lady Crumpet tries to civilize him"],
    tabooAvoid: "Avoid class caricature; make him competent chaos.",
  },

  // North Korea
  {
    id: "nk_marshal_pungsan", country: "North Korea", factionId: 8, breed: "Dark Pungsan", name: "Marshal Bonepaw", lane: "commander", tone: ["heel", "comic"], role: "Grandiose parade sorcerer / propaganda boss", boardRef: board("North Korea"),
    visualDesign: "Dark Pungsan in medal-heavy uniform, oversized hat, stamped state pickaxe, chest-out theatrical menace.",
    publicMask: "Loudest beast in history, according to himself.",
    hiddenWant: "Wants to know whether the room laughs at him.",
    flaw: "Gets louder whenever reality whispers.",
    voice: "Grandiose propaganda bombast, all superlatives, comic-villain volume.",
    comedyLoop: "He declares historic victory before anything starts, then blames physics.",
    suspenseLoop: "What happens when Marshal's performance finally stops being funny?",
    actionWow: "A parade-microphone blast turns synchronized chairs into a marching wall.",
    powerStyle: "Red banner blocks, brass parade hits, stamp-impact magic, loudspeaker shockwaves.",
    engagementUse: "Use for over-the-top heel comedy, crowd staging, authoritarian theater satire.",
    relationshipSeeds: ["Lady Crumpet defeats him with etiquette", "Bao thinks he is inefficient", "Pip is accidentally honest with him"],
    tabooAvoid: "No real leader likeness/names; satire the fictional faction theater.",
  },
  {
    id: "nk_pungsan_defector_comic", country: "North Korea", factionId: 8, breed: "Pungsan", name: "Comrade Button", lane: "muggle", tone: ["sincere", "comic"], role: "Control-room button guard / accidental truth teller", boardRef: board("North Korea"),
    visualDesign: "Pungsan in oversized control-room uniform, red button key, nervous eyes, too-formal posture.",
    publicMask: "Obedient guard who repeats official lines one beat too late.",
    hiddenWant: "Wants someone to ask what he thinks before he presses the button.",
    flaw: "Freezes when choice becomes personal.",
    voice: "Formal, nervous, small pauses; accidental honesty.",
    comedyLoop: "He whispers the truth because he thinks the microphone is off.",
    suspenseLoop: "Will Button press the order, or finally choose his own beat?",
    actionWow: "His hesitant paw stops a whole parade machine mid-step.",
    powerStyle: "Red button glow, loudspeaker hum, fluorescent silence, tiny paw tremor.",
    engagementUse: "Use for sincere pivots inside authoritarian comedy, tension, moral choice.",
    relationshipSeeds: ["Pip sees him as another scared small character", "Marshal terrifies him", "Agent Woolf wants his testimony"],
    tabooAvoid: "Handle with dignity; do not mock suffering.",
  },
  {
    id: "nk_northern_spitz_chorus", country: "North Korea", factionId: 8, breed: "Northern Spitz", name: "Choir Frost", lane: "wizard", tone: ["mystery", "action"], role: "Synchronized choir mage / crowd-control conductor", boardRef: board("North Korea"),
    visualDesign: "Northern Spitz with conductor cape, icy white fur, baton-pickaxe, rows of abstract chorus silhouettes behind.",
    publicMask: "Elegant conductor whose crowd moves as one body.",
    hiddenWant: "Wants a solo but only knows chorus.",
    flaw: "Cannot improvise unless the whole room does it with him.",
    voice: "Musical, controlled, eerie calm with sudden choral power.",
    comedyLoop: "He tries to make one casual conversation happen in perfect unison.",
    suspenseLoop: "Who is singing the note Choir Frost did not conduct?",
    actionWow: "A baton flick freezes a crowd in a perfect wave while one rebel note keeps moving.",
    powerStyle: "Choral drones, white-blue waveforms, baton cuts, synchronized motion.",
    engagementUse: "Use for crowd spectacle, eerie control, musical comedy, rebellion hints.",
    relationshipSeeds: ["Jin sees choreography rivalry", "Bao admires the control", "Button hears the wrong note first"],
    tabooAvoid: "No real propaganda songs; use abstract choir motifs.",
  },
  {
    id: "nk_paektu_wolf_dog", country: "North Korea", factionId: 8, breed: "Paektu Wolf-Dog", name: "Paektu Static", lane: "operator", tone: ["thriller", "mystery"], role: "Mountain broadcast saboteur / signal wolf", boardRef: board("North Korea"),
    visualDesign: "Wolf-dog silhouette in mountain comms coat, cracked radio core, red static eye-glint, rugged stealth posture.",
    publicMask: "Silent technician who fixes broadcasts by breaking them.",
    hiddenWant: "Wants the truth out, but only as static nobody can trace.",
    flaw: "Trusts signals more than allies.",
    voice: "Sparse, whispery, radio-static edges; rarely speaks.",
    comedyLoop: "His idea of a joke is replacing a speech with elevator music.",
    suspenseLoop: "Which broadcast did Paektu Static secretly leak to the outside MineBTC world?",
    actionWow: "A red-static pulse cuts every screen except one hidden mountain feed.",
    powerStyle: "Radio static, mountain fog, red scanlines as abstract light, hard signal cuts.",
    engagementUse: "Use for leak plots, thriller cliffhangers, information warfare without real claims.",
    relationshipSeeds: ["Nova and Misha detect him", "Bao wants him erased", "Button may be his only friend"],
    tabooAvoid: "No real cyber accusations; keep it fictional broadcast sabotage.",
  },

  // France
  {
    id: "france_bulldog_couture", country: "France", factionId: 9, breed: "French Bulldog", name: "Madame Mint", lane: "commander", tone: ["comic", "shady"], role: "Couture treasury designer / luxury floor defender", boardRef: board("France"),
    visualDesign: "French Bulldog in high-fashion mining armor, gold-trim cape, espresso charm, unimpressed runway posture.",
    publicMask: "Fashion tyrant who treats ugly strategy as a moral failure.",
    hiddenWant: "Wants beauty to matter in a war measured by numbers.",
    flaw: "Would rather lose stylishly than win ugly, until she secretly fixes both.",
    voice: "Suave French-accented English, elegant insults, effortless disdain.",
    comedyLoop: "She pauses a battle to redesign the villain's cape.",
    suspenseLoop: "Did Madame Mint hide the treasury key inside the outfit?",
    actionWow: "Gold thread whips from her cape and stitches a broken floor into a trap.",
    powerStyle: "Couture gold thread, espresso-cup clink, runway spotlight, burgundy shadows.",
    engagementUse: "Use for luxury comedy, shady treasury, aesthetic rivalry, visual flex.",
    relationshipSeeds: ["Rublefang wants her designer contracts", "Sir Pound respects the old-money shade", "Darya admires her beauty logic"],
    tabooAvoid: "Avoid making France only romance/Eiffel; use style, institutions, cafe, art, finance.",
  },
  {
    id: "france_poodle_philosopher", country: "France", factionId: 9, breed: "Poodle", name: "Professor Croissant", lane: "wizard", tone: ["comic", "sincere"], role: "Cafe philosopher / theory mage", boardRef: board("France"),
    visualDesign: "Poodle scholar with cafe scarf, chalk-pick wand, pastry box, elegant curls, intense debating face.",
    publicMask: "Intellectual who can turn any mistake into a theory.",
    hiddenWant: "Wants to be useful, not merely brilliant.",
    flaw: "Explains the door instead of opening it.",
    voice: "Philosophical, witty, theatrical; pauses for imaginary footnotes.",
    comedyLoop: "He wins an argument nobody knew was happening while the room floods.",
    suspenseLoop: "Which ridiculous theory is actually correct about degenBTC?",
    actionWow: "Chalk equations from a cafe table become a glowing bridge across a gap.",
    powerStyle: "Chalk sigils, accordion-ish flourish, cream/gold cafe light, pastry-box foley.",
    engagementUse: "Use for clever exposition, comedy theory, soft emotional wisdom.",
    relationshipSeeds: ["Chairman Biscuit hates his monetary philosophy", "Pip asks the question that stumps him", "Madame Mint edits his scarf mid-sentence"],
    tabooAvoid: "Do not turn into long lectures; action or joke must carry theory.",
  },
  {
    id: "france_papillon_duelist", country: "France", factionId: 9, breed: "Papillon", name: "Fleur Flash", lane: "trickster", tone: ["action", "comic"], role: "Tiny boulevard duelist / attention thief", boardRef: board("France"),
    visualDesign: "Papillon with wing-like ears, rapier-pick charm, velvet jacket, dramatic tiny silhouette.",
    publicMask: "Tiny duelist convinced the camera exists for her entrance.",
    hiddenWant: "Wants rivals to stop calling her small before she proves it.",
    flaw: "Over-choreographs every entrance.",
    voice: "Fast, theatrical, flirtatious challenge energy; sharp laugh.",
    comedyLoop: "She demands a duel over a seating arrangement.",
    suspenseLoop: "What insult will finally make Fleur stop performing and fight seriously?",
    actionWow: "Her ears/cape create butterfly-shaped afterimages that redirect attacks.",
    powerStyle: "Butterfly cuts, velvet flashes, cafe-chair impacts, tiny rapier chimes.",
    engagementUse: "Use for short-form action, comic pride, romance-flirt tension, underdog scale jokes.",
    relationshipSeeds: ["Lady Crumpet is her etiquette rival", "Pint Rocket ruins her dramatic timing", "Jin wants her entrance choreography"],
    tabooAvoid: "No romance-only reduction; she is combat-capable.",
  },
  {
    id: "france_picard_union", country: "France", factionId: 9, breed: "Berger Picard", name: "Luc Barricade", lane: "muggle", tone: ["hero", "comic"], role: "Union organizer / street barricade engineer", boardRef: board("France"),
    visualDesign: "Berger Picard with work jacket, rolled posters as abstract shapes, cobblestone shield, practical serious eyes.",
    publicMask: "Organizer who can turn five cafe chairs into a revolution.",
    hiddenWant: "Wants the small miners to stop being background extras.",
    flaw: "Schedules a protest before checking if anyone agrees.",
    voice: "Rough, earnest, sarcastic, street-level French energy.",
    comedyLoop: "He calls a strike against bad lighting.",
    suspenseLoop: "Will Luc's crowd save France or hijack the whole game economy?",
    actionWow: "Cobblestones rise into a defensive barricade as cafe chairs lock together.",
    powerStyle: "Cobblestone geometry, poster-paper flutters, brass street rhythm, warm crowd hum.",
    engagementUse: "Use for crowd action, social proof, working-class hero beats, France faction politics.",
    relationshipSeeds: ["Chai Alpha loves his grassroots tactics", "Madame Mint pretends not to need him", "Agent Woolf watches the crowd math"],
    tabooAvoid: "Keep strikes/protests fictional and funny, not real unrest footage.",
  },

  // Brazil
  {
    id: "brazil_caramelo_striker", country: "Brazil", factionId: 10, breed: "Caramelo Vira-Lata", name: "Sol Caramelo", lane: "underdog", tone: ["hero", "comic"], role: "Street-football striker / solar comeback beast", boardRef: board("Brazil"),
    visualDesign: "Caramelo street dog with football boots, sun-gold scarf, patched jersey armor, bright grin, impossible balance.",
    publicMask: "Happy street striker who jokes until the final minute.",
    hiddenWant: "Wants the world to stop treating Brazil as vibes without strategy.",
    flaw: "Celebrates before securing the ball.",
    voice: "Warm Brazilian energy, musical, playful, sudden competitive fire.",
    comedyLoop: "He turns every object into a football, including dangerous ones.",
    suspenseLoop: "Can Sol steal the mine in the final minute again?",
    actionWow: "A bicycle-kick sends a solar flare across a concrete court and flips the scoreboard.",
    powerStyle: "Solar flare trails, football chant percussion, green/yellow/blue sparks, mosaic ground glow.",
    engagementUse: "Use for comeback clips, high-energy hooks, underdog joy, sports virality.",
    relationshipSeeds: ["Raja loves the sports drama", "Kiro studies his impossible timing", "Pint Rocket starts chants for him"],
    tabooAvoid: "Do not make Brazil only carnival/beach; use football, community, ambition, joy, strategy.",
  },
  {
    id: "brazil_fila_treasury", country: "Brazil", factionId: 10, breed: "Fila Brasileiro", name: "Dona Vaulta", lane: "commander", tone: ["shady", "sincere"], role: "Treasury matriarch / favela vault protector", boardRef: board("Brazil"),
    visualDesign: "Powerful Fila Brasileiro in emerald-gold vault cloak, heavy key necklace, protective mother-boss energy.",
    publicMask: "Warm community protector who smiles while locking the vault.",
    hiddenWant: "Wants Brazil's wins to feed the block, not disappear upward.",
    flaw: "Trusts family systems more than transparent systems.",
    voice: "Low, warm, commanding; affectionate threat energy.",
    comedyLoop: "She feeds everyone before interrogating them.",
    suspenseLoop: "Who is Dona Vaulta hiding inside the treasury?",
    actionWow: "A key necklace turns into golden favela-stair geometry sealing every exit.",
    powerStyle: "Emerald/gold vault light, percussion heartbeat, staircase sigils, warm shadow.",
    engagementUse: "Use for treasury drama, community stakes, shady-but-loving authority.",
    relationshipSeeds: ["Rublefang wants access; she calls him skinny", "Madame Mint respects the vault style", "Sol owes her more than money"],
    tabooAvoid: "Avoid poverty spectacle; show community power and luxury mix.",
  },
  {
    id: "brazil_terrier_carnival_hacker", country: "Brazil", factionId: 10, breed: "Brazilian Terrier", name: "Luma Loop", lane: "trickster", tone: ["comic", "mystery"], role: "Carnival workshop hacker / rhythm illusionist", boardRef: board("Brazil"),
    visualDesign: "Brazilian Terrier with workshop goggles, feather-texture cape accents, drum-controller belt, prankster eyes.",
    publicMask: "Party engineer who says every exploit is just rhythm.",
    hiddenWant: "Wants to be known as genius, not just fun.",
    flaw: "Hides plans inside jokes until nobody follows the plan.",
    voice: "Fast, playful, rhythmic, teasing; laughs while debugging chaos.",
    comedyLoop: "Her 'sound check' accidentally hacks three countries.",
    suspenseLoop: "Which beat in Luma's music contains the real attack?",
    actionWow: "Drum hits become visible waveform steps that characters run across.",
    powerStyle: "Percussion waveforms, carnival workshop light, neon feathers as texture, joyful glitch.",
    engagementUse: "Use for viral music, rhythm action, comedy tech, surprise hacks.",
    relationshipSeeds: ["Nari wants her rhythm engine", "Momo wants the broadcast rights", "Sol thinks she is fun until she wins"],
    tabooAvoid: "Do not make carnival the whole country; use it as craft/workshop intelligence.",
  },
  {
    id: "brazil_dogo_amazon", country: "Brazil", factionId: 10, breed: "Brazilian Dogo", name: "Mato Verde", lane: "operator", tone: ["action", "mystery"], role: "Amazon route guardian / green-energy scout", boardRef: board("Brazil"),
    visualDesign: "Brazilian Dogo in jungle-tech armor, leaf-shaped power core, river-map bracer, quiet intense posture.",
    publicMask: "Silent scout who knows routes the map refuses to show.",
    hiddenWant: "Wants the war to respect the land, not just extract value.",
    flaw: "Distrusts city players before they fail.",
    voice: "Low, spare, grounded; nature metaphors without preaching.",
    comedyLoop: "He treats elite tech like a broken compass.",
    suspenseLoop: "What did Mato find under the green route that could change emissions?",
    actionWow: "Emerald roots/circuitry lift a broken path into a living bridge.",
    powerStyle: "Emerald bio-circuitry, river reflections, low drum, leaf-core pulse.",
    engagementUse: "Use for landscape wow, resource mystery, action scouting, green power contrast.",
    relationshipSeeds: ["Tara understands guardian duty", "Nova maps him poorly", "Dona Vaulta funds him secretly"],
    tabooAvoid: "Avoid simplistic jungle exoticism; make him high-tech and grounded.",
  },

  // Israel
  {
    id: "israel_canaan_cyber", country: "Israel", factionId: 11, breed: "Canaan Dog", name: "Yalla Zero", lane: "operator", tone: ["shady", "action"], role: "Cyber-startup commando / exploit hunter", boardRef: board("Israel"),
    visualDesign: "Canaan Dog in desert-tech tactical hoodie, blue-white circuit scarf, laptop gauntlet, sharp streetwise eyes.",
    publicMask: "Blunt cyber founder who says 'small bug' before breaking a fortress.",
    hiddenWant: "Wants to prove small countries can out-think giant ones.",
    flaw: "Treats people like systems to penetrate.",
    voice: "Fast, blunt Israeli-accented English, dry chutzpah, zero patience.",
    comedyLoop: "He fixes the enemy's security because it offended him.",
    suspenseLoop: "Did Yalla Zero patch the MineBTC system, or install a door?",
    actionWow: "A blue-white exploit grid opens one frame of impossible access, then vanishes.",
    powerStyle: "Desert-tech cyan, command-line sparks without readable text, sharp glitch cuts, bass click.",
    engagementUse: "Use for cyber suspense, small-country outsmarting, AGI/security plots, action hacks.",
    relationshipSeeds: ["Nova dislikes his access", "Jugaad Byte respects his shortcuts", "Agent Woolf follows his fingerprints"],
    tabooAvoid: "No real conflict claims; keep cyber as fictional game-world security.",
  },
  {
    id: "israel_baladi_market", country: "Israel", factionId: 11, breed: "Baladi Dog", name: "Shuk Ember", lane: "trickster", tone: ["comic", "sincere"], role: "Market negotiator / street-food morale captain", boardRef: board("Israel"),
    visualDesign: "Baladi dog with market-stall apron armor, ceramic plate shield, spice pouch charms, warm mischievous face.",
    publicMask: "Street negotiator who feeds rivals while bargaining.",
    hiddenWant: "Wants people to see community before conflict.",
    flaw: "Turns every emotional problem into a deal over food.",
    voice: "Warm, blunt, teasing, street-smart; 'yalla' energy but not overdone.",
    comedyLoop: "He negotiates a ceasefire over who gets the last plate.",
    suspenseLoop: "Which favor did Shuk Ember trade to keep Israel in the race?",
    actionWow: "Spice smoke forms a temporary shield-map around the market table.",
    powerStyle: "Spice smoke, ceramic clacks, warm limestone light, street percussion.",
    engagementUse: "Use for ordinary-life comedy, warmth, market deals, soft diplomacy.",
    relationshipSeeds: ["Saffron Ledger is his negotiation rival", "Chai Alpha respects the hustle", "Yalla Zero pretends he does not need morale"],
    tabooAvoid: "Avoid reducing country to security; show market, tech, desert, community.",
  },
  {
    id: "israel_pointer_drone", country: "Israel", factionId: 11, breed: "Israel Pointer", name: "Mira Lock", lane: "commander", tone: ["mystery", "action"], role: "Drone tactician / desert-grid commander", boardRef: board("Israel"),
    visualDesign: "Israel Pointer with desert command coat, small drone flock, map-scarf, calm hawk-like gaze.",
    publicMask: "Tactician who sees the battlefield as geometry.",
    hiddenWant: "Wants to prevent chaos, but control keeps asking for more control.",
    flaw: "Over-watches until trust becomes impossible.",
    voice: "Controlled, analytical, terse; warmth appears as tactical advice.",
    comedyLoop: "She sends a drone to check if someone is lying about lunch.",
    suspenseLoop: "Who is Mira watching that even Yalla Zero does not know about?",
    actionWow: "Drones form a Star-of-map-like tactical lattice without literal symbols, redirecting attacks.",
    powerStyle: "Cyan drone lattice, desert sun glare, soft rotor hum, sand-grid overlays.",
    engagementUse: "Use for surveillance thriller, strategy, desert landscape, precision action.",
    relationshipSeeds: ["Nova debates airspace with her", "Nilo Mirage evades her", "Agent Woolf wants her files"],
    tabooAvoid: "No real military operations; keep drone tactics fantasy/game-world.",
  },
  {
    id: "israel_negev_desert_dog", country: "Israel", factionId: 11, breed: "Negev Desert Dog", name: "Negev Bloom", lane: "wizard", tone: ["hero", "sincere"], role: "Desert-water alchemist / survival engineer", boardRef: board("Israel"),
    visualDesign: "Negev Desert Dog in sand-and-cyan robes, water-core staff, desert goggles, hopeful grounded expression.",
    publicMask: "Quiet engineer who grows miracles instead of announcing them.",
    hiddenWant: "Wants survival tech to matter more than war tech.",
    flaw: "Understates breakthroughs until others take credit.",
    voice: "Soft, practical, hopeful; engineering clarity with desert calm.",
    comedyLoop: "He saves a dramatic villain with irrigation and acts like it is routine maintenance.",
    suspenseLoop: "What can Negev Bloom grow inside a dead mining zone?",
    actionWow: "A water-core staff sends cyan roots through cracked stone, turning a dead floor luminous.",
    powerStyle: "Water-core cyan, sand-gold light, root circuitry, gentle chime.",
    engagementUse: "Use for sincere pivots, rebirth, science-wonder, hopeful payoff after thriller.",
    relationshipSeeds: ["Mato Verde understands him", "Darya trades poems with him", "Yalla Zero thinks hope needs better security"],
    tabooAvoid: "No miracle-tech savior cliche; show constraints and cost.",
  },
];

export function resolveCountryCharacterProfile(idOrTag: string): CountryCharacterProfile | null {
  const key = String(idOrTag || "").trim().replace(/^@/, "").toLowerCase();
  return COUNTRY_CHARACTER_PROFILES.find((p) => p.id === key) || null;
}

export function profilesForCountry(country: string): CountryCharacterProfile[] {
  const key = country.toLowerCase();
  return COUNTRY_CHARACTER_PROFILES.filter((p) => p.country.toLowerCase() === key);
}

export function buildCountryCastPromptBlock(): string {
  const knownCountries = new Set(listCountryBoardEntries().map((c) => c.country));
  const byCountry = new Map<string, CountryCharacterProfile[]>();
  for (const profile of COUNTRY_CHARACTER_PROFILES) {
    if (!knownCountries.has(profile.country)) continue;
    const arr = byCountry.get(profile.country) || [];
    arr.push(profile);
    byCountry.set(profile.country, arr);
  }

  const countryBlocks = [...byCountry.entries()].map(([country, profiles]) => {
    const entries = profiles.map((p) => [
      `- @${p.id} (${p.breed}) ${p.name}: ${p.role}.`,
      `  Look: ${p.visualDesign}`,
      `  Personality: mask=${p.publicMask}; hidden want=${p.hiddenWant}; flaw=${p.flaw}.`,
      `  Voice: ${p.voice}`,
      `  Loops: comedy=${p.comedyLoop}; suspense=${p.suspenseLoop}; wow=${p.actionWow}.`,
      `  Power: ${p.powerStyle}`,
      `  Use: ${p.engagementUse}`,
      `  Refs: ${p.boardRef}`,
    ].join("\n"));
    return `${country}\n${entries.join("\n")}`;
  });

  return [
    "COUNTRY CHARACTER REGISTRY:",
    "These are reusable MineBTC show archetypes grounded in country-level institutions, cultural production, economics, sport, technology, and geopolitical posture. They are fictional HashBeasts, not real people.",
    "Use them for story ideas, dialogue POV, relationship arcs, and frame refs. Until a dedicated individual sheet exists, @profile refs resolve to that country's character board; add the board ref in startFrame.refs for consistency.",
    "Safety: satire institutions and faction behavior, never real named politicians, real hate symbols, real slogans, or ethnicity as the joke.",
    ...countryBlocks,
  ].join("\n\n");
}
