/**
 * Render ONE scene to a COMPLETE clip — keyframe → motion video → voiced dialogue
 * → lip-sync (or mux) → SFX → normalized 1080p + burned caption. Each scene comes
 * out finished so the orchestrator can do them one at a time (with approval).
 *
 * Grounding: character shots are generated by editing the cast's LOCKED reference
 * images (cast.ts) so every beast stays on-model + consistent across shots/videos.
 * No-character shots render as a mood-tinted plate (cheap, reliable) — flip
 * TRAILER_AI_SCENERY later for generated scenery.
 */
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { generateImageEditFromBuffers, generateVideoFromFrames, uploadBufferToS3, lipSyncVideo } from "../../src/utils/falMedia.js";
import { resolveCharacter, ensureCharacterRefs } from "./cast.js";
import { synthesizeShotDialogue, resolveSfx } from "./audio.js";
import { plateClip, stillToClip, muxAudio, overlaySfx, normalizeAndCaption, probeDuration } from "./ffmpeg.js";
import type { Shot } from "../pipeline/types.js";
import { buildTrailerKeyframePrompt, buildTrailerMotionPrompt } from "../style/visualBible.js";

const IMG_RES = (process.env.TRAILER_IMAGE_RES as "1K" | "2K") || "2K";
const VIDEO_RES = process.env.TRAILER_VIDEO_RES || "1080p";
const SEEDANCE_MAX = Math.min(12, Math.max(4, Number(process.env.TRAILER_SEEDANCE_MAX_SEC || 10)));
const MIN_SEC = Math.max(2, Number(process.env.TRAILER_SHOT_MIN_SEC || 3));
const TAIL_SEC = Math.max(0, Number(process.env.TRAILER_SHOT_TAIL_SEC || 0.6));
// Lip-sync OFF by default: sync.so can't animate a 2D/muzzle mouth (leaves it
// shut) — we drive talking via the keyframe (open mouth) + i2v motion instead.
const LIPSYNC_GLOBAL = process.env.TRAILER_LIPSYNC === "true"; // opt-in per run; per-shot can still force
const DEBUG = process.env.TRAILER_DEBUG !== "false";
const SAVE_PROMPTS = process.env.TRAILER_SAVE_PROMPTS === "true";

const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));
const step = (shot: Shot, label: string) => {
  if (DEBUG) process.stdout.write(`\n      shot ${shot.n}: ${label}… `);
};

/** Lip-sync this shot? per-shot flag wins; else heuristic: a talking character in a close/medium shot. */
function shouldLipsync(shot: Shot, hasCharacters: boolean, hasDialogue: boolean): boolean {
  if (!LIPSYNC_GLOBAL || !hasCharacters || !hasDialogue) return false;
  if (typeof shot.lipsync === "boolean") return shot.lipsync;
  const cam = (shot.camera || "").toLowerCase();
  if (/wide|establishing|aerial|crane|long shot/.test(cam)) return false; // face too small
  return true; // close-up / medium / over-the-shoulder → sync the mouth
}

/** Mood → plate tint for no-character shots. */
function moodTint(mood: string): [number, number, number] {
  const m = (mood || "").toLowerCase();
  if (/red|danger|war|alarm|anger/.test(m)) return [40, 8, 10];
  if (/gold|triumph|hope|warm/.test(m)) return [40, 28, 8];
  if (/eerie|cold|tense|dark|ominous/.test(m)) return [8, 10, 18];
  if (/sad|melanchol|quiet|soft/.test(m)) return [12, 14, 22];
  return [10, 10, 14];
}

export interface RenderSceneOptions { promptDumpDir?: string; }
export interface RenderSceneResult { buffer: Buffer; lipsynced: boolean; aiShot: boolean; seconds: number; }

function dumpPromptFile(dir: string | undefined, name: string, content: string): void {
  if (!SAVE_PROMPTS || !dir) return;
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, name), content);
}

function describeRefs(charDefs: NonNullable<ReturnType<typeof resolveCharacter>>[], refCount: number): string {
  const lines = [`runtime reference image count: ${refCount}`];
  for (const def of charDefs) {
    lines.push(`character ${def.id}: ${def.aliases.join(", ")}`);
    const refs = def.localReferencePaths || [];
    if (refs.length === 0) lines.push(`  fallback generated/cached ref: trailer/cast/${def.id}.png`);
    for (const [i, ref] of refs.entries()) lines.push(`  ref ${i + 1}: ${ref}${fs.existsSync(ref) ? "" : " (missing)"}`);
  }
  return lines.join("\n");
}

/** Render a single shot into a finished scene clip. `scratch` namespaces S3 uploads. */
export async function renderScene(shot: Shot, scratch: string, opts: RenderSceneOptions = {}): Promise<RenderSceneResult> {
  const charDefs = (shot.characters || []).map((c) => resolveCharacter(c.name)).filter(Boolean) as NonNullable<ReturnType<typeof resolveCharacter>>[];
  const hasCharacters = charDefs.length > 0;

  // 1. dialogue audio FIRST (its duration sizes the clip → the line always fits)
  const dlg = await synthesizeShotDialogue(shot.dialogue || []);
  const hasDialogue = !!dlg;
  const targetSec = clamp(Math.ceil(Math.max(shot.durationSec || MIN_SEC, (dlg?.durationSec || 0) + TAIL_SEC)), MIN_SEC, SEEDANCE_MAX);

  // 2. silent base video
  let silent: Buffer;
  if (hasCharacters) {
    step(shot, "loading character refs");
    const refGroups = await Promise.all(charDefs.map((d) => ensureCharacterRefs(d)));
    const refs = refGroups.flat().slice(0, 8).map((buffer) => ({ buffer, mime: "image/png" as const }));
    step(shot, "generating keyframe");
    const prompt = buildTrailerKeyframePrompt(shot, { hasDialogue });
    const shotPrefix = `shot_${String(shot.n).padStart(2, "0")}`;
    dumpPromptFile(opts.promptDumpDir, `${shotPrefix}_runtime_reference_images.txt`, describeRefs(charDefs, refs.length));
    dumpPromptFile(opts.promptDumpDir, `${shotPrefix}_runtime_nano_banana_keyframe_prompt.txt`, prompt);
    const keyframe = await generateImageEditFromBuffers(prompt, refs, { aspectRatio: "16:9", resolution: IMG_RES });
    step(shot, "uploading keyframe");
    const kfUrl = await uploadBufferToS3(`${scratch}/shot${shot.n}_kf.png`, keyframe.buffer, "image/png");
    step(shot, "generating Seedance video");
    const motion = buildTrailerMotionPrompt(shot, { hasDialogue });
    dumpPromptFile(opts.promptDumpDir, `${shotPrefix}_runtime_seedance_motion_prompt.txt`, motion);
    const vid = await generateVideoFromFrames(motion, kfUrl, undefined, { durationSecs: targetSec, resolution: VIDEO_RES, aspectRatio: "16:9" });
    silent = vid.buffer;
  } else {
    // no-character shot → mood-tinted plate with a slow push (reliable, cheap)
    silent = await plateClip(targetSec, moodTint(shot.mood));
  }

  // 3. lay the voice on the clip — lip-sync hero talking shots, else mux
  const lipsync = shouldLipsync(shot, hasCharacters, hasDialogue);
  let voiced = silent;
  if (dlg) {
    if (lipsync) {
      try {
        step(shot, "uploading lip-sync inputs");
        const vUrl = await uploadBufferToS3(`${scratch}/shot${shot.n}_v.mp4`, silent, "video/mp4");
        const aUrl = await uploadBufferToS3(`${scratch}/shot${shot.n}_a.mp3`, dlg.buffer, "audio/mpeg");
        step(shot, "lip-syncing");
        voiced = (await lipSyncVideo(vUrl, aUrl)).buffer;
      } catch { voiced = await muxAudio(silent, dlg.buffer); }
    } else {
      step(shot, "muxing dialogue");
      voiced = await muxAudio(silent, dlg.buffer);
    }
  }

  // 4. SFX (per shot — local library or AI-generated from shot.sfx)
  try {
    if (shot.sfx) step(shot, "resolving SFX");
    const sfx = await resolveSfx(shot.sfx, targetSec);
    if (sfx) voiced = await overlaySfx(voiced, sfx);
  } catch { /* skip */ }

  // 5. normalize to 1080p + burn the on-screen caption (facts live here)
  step(shot, "normalizing/captioning");
  const buffer = await normalizeAndCaption(voiced, shot.caption);
  const seconds = await probeDuration(buffer);
  return { buffer, lipsynced: lipsync, aiShot: hasCharacters, seconds };
}
